baseURL = "https://ackten.com/"
languageCode = "en-US"
title = "Ackten"
summaryLength = "20"
DefaultContentLanguage = "en"

# navigation
[menu]

    [[menu.nav]]
    name = "Integrations"
    URL = "/service"
    weight = 3

    [[menu.nav]]
    name = "Pricing"
    URL = "/pricing"
    weight = 5

    [[menu.nav]]
    name = "Contact"
    URL = "/contact"
    weight = 8


[params]
logo = "images/logo.png"
mail = "info@ackten.com"
mobile = "1234565523"
home = "Home"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "39.7392"
mapLongitude = "104.9903"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-136686652-1"

# mailchimp subsciption
mailchimpFormAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e" # replace this url with yours
mailchimpFormName = "b_f95ece2732a6e9925f2e70a61_b1e227529e" # replace this code with yours


  # meta data
  [[params.meta]]
  name = "description"
  content = "this it a content"

  [[params.meta]]
  name = "keywords"
  content = "this it a content"

    # Login Link
    [params.loginLink]
    btnText = "Login"
    btnURL = "https://dashboard.ackten.com/"


    # Quote Button
    [params.quoteBtn]
    enable = true
    btnText = "Join Private Beta"
    btnURL = "/beta"

    # about
    [params.about]
    enable = true
    bgImage = "images/background/about-bg.jpg"
    title = "Who We Are?"
    description = "We are developers, product managers, and scrummasters who are looking to improve their teams workflow so they can be more productive."

    [params.about.btn]
    enable = true
    btnText = "Explore Integrations"
    btnURL = "#integrations"

        [[params.about.listLeft]]
        listItem = "Pull Request Reminders"

        [[params.about.listLeft]]
        listItem = "Product Review Alerts"

        [[params.about.listLeft]]
        listItem = "GitFlow Enforcement"

        [[params.about.listRight]]
        listItem = "Broken Build Blame"

        [[params.about.listRight]]
        listItem = "Advanced Pull Requests"

        [[params.about.listRight]]
        listItem = "TDD Enforcement"

    # cta
    [params.cta]
    enable = true
    bgImage = "images/background/cta.jpg"
    title = "Ackten gives the smart solution for your business"
    btnText = "Join Beta"
    btnURL = "/beta"

    # clients Logo Slider
    [params.logoSlider]
    enable = true
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"

        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

    # footer
    [params.footer]
    logo = "images/logo-footer.png"
    content = "Bring together your systems to make your developers, product owners and managers more effective."


    # quickLinks
    quickLink = "Quick Link"

    # subscribe
    subscribe = "Join Private Beta"
    subscribeContent = "Enter your email here to join our private beta, we swear not to spam."

    # copyright
    copyright = "Ackten</span> &copy; 2019 All Right Reserved"

        # social icon
        [[params.footer.socialIcon]]
        icon = "ti-facebook"
        URL = "#"

        [[params.footer.socialIcon]]
        icon = "ti-twitter-alt"
        URL = "#"

        [[params.footer.socialIcon]]
        icon = "ti-vimeo-alt"
        URL = "#"

        [[params.footer.socialIcon]]
        icon = "ti-linkedin"
        URL = "#"


        # quick links
        [[params.footer.quickLinks]]
        quickLinkItem = "Pricing"
        URL = "/pricing"

        [[params.footer.quickLinks]]
        quickLinkItem = "FAQs"
        URL = "#"

        [[params.footer.quickLinks]]
        quickLinkItem = "Contact Us"
        URL = "/beta"

        [[params.footer.quickLinks]]
        quickLinkItem = "Integrations"
        URL = "/service"


        # bottom links
        [[params.footer.links]]
            name = "Legal"
            URL = "#"

        [[params.footer.links]]
            name = "Sitemap"
            URL = "#"

        [[params.footer.links]]
            name = "Privacy Policy"
            URL = "#"

        [[params.footer.links]]
            name = "Terms & Conditions"
            URL = "#"

    # share blog post
    [[params.sharePost]]
    icon = "ti-facebook"
    URL = "#"

    [[params.sharePost]]
    icon = "ti-twitter-alt"
    URL = "#"

    [[params.sharePost]]
    icon = "ti-linkedin"
    URL = "#"

    [[params.sharePost]]
    icon = "ti-google"
    URL = "#"



